project:
  type: website

pagetitle: "{{< meta title >}} | {{< meta website.title >}}"

website:
  title: Sebastian Dunnett
  favicon: images/favicon.png
  twitter-card: true
  open-graph: true
  navbar:
    #logo: images/sd.svg
    left:
      - href: index.qmd
        text: About
      - href: posts.qmd
        text: Posts
      - href: publications.qmd
        text: Research
      - href: talks.qmd
        text: Talks
    right:
      - icon: twitter
        href: https://twitter.com/sebdunnett
      - icon: linkedin
        href: https://www.linkedin.com/in/sebastiandunnett/
      - icon: github
        href: https://github.com/sebdunnett
      - icon: envelope
        href: mailto:sebdunnett@gmail.com
      - href: resources/SDunnett_CV.pdf
        text: CV
  page-footer:
    center: |
      <span class="faux-block">{{< fa brands creative-commons title="copyright" >}} 2023 Sebastian Dunnett</span>
      
format:
  html:
    theme:
      light: light.scss
      dark: dark.scss
    mainfont: Mulish
    toc: true
    code-fold: show
    code-summary: "Show/hide code"
    code-block-border-left: "#bc4749"
    code-block-bg: "transparent"
    highlight-style: solarized

