project:
  type: website

pagetitle: "{{< meta title >}} | {{< meta website.title >}}"

website:
  title: Sebastian Dunnett
  favicon: images/favicon.png
  navbar:
    logo: images/sd.svg
    left:
      - href: index.qmd
        text: About
      - href: posts.qmd
        text: Posts
      - href: publications.qmd
        text: Publications
      - icon: twitter
        href: https://twitter.com/sebdunnett
      - icon: linkedin
        href: https://www.linkedin.com/in/sebastiandunnett/
      - icon: github
        href: https://github.com/sebdunnett
      - icon: envelope
        href: mailto:sebdunnett@gmail.com
      - href: resources/SDunnett_CV.pdf
        text: CV

format:
  html:
    theme:
      light: light.scss
      dark: dark.scss
    #Lato,Mulish,Merriweather,Alegreya,Arvo,Josefin Slab,Poppins
    mainfont: Mulish
    toc: true

