project:
  type: website

website:
  navbar:
    favicon: images/favicon.ico
    logo: images/sd.png
    left:
      - href: index.qmd
        text: Home
      - href: posts.qmd
        text: My Blog
      - href: publications.qmd
        text: Publications
      - icon: twitter
        href: https://twitter.com/sebdunnett
      - icon: linkedin
        href: https://www.linkedin.com/in/sebastiandunnett/
      - icon: github
        href: https://github.com/sebdunnett
      - icon: mailbox2
        href: mailto:sebdunnett@gmail.com

format:
  html:
    theme:
    - simplex
    - styles.css
    toc: true

