project:
  type: website

website:
  title: "Sebastian Dunnett, PhD"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: publications.qmd
        text: Publications

format:
  html:
    theme: simplex
    css: styles.css
    toc: true

editor: visual

