---
pagetitle: "Research | Sebastian Dunnett"
---

# 2022

**Dunnett, S.**, Holland, R. A., Taylor, G., & Eigenbrod, F. (2022a). Predicted wind and solar energy expansion has minimal overlap with multiple conservation priorities across global regions. *Proceedings of the National Academy of Sciences*, *119*(6). [{{< fa link title="link" >}}](https://doi.org/10.1073/pnas.2104764119)

**Dunnett, S.**, Holland, R. A., Taylor, G., & Eigenbrod, F. (2022b). Reply to Pérez-García et al.: Perfect is the enemy of good. *Proceedings of the National Academy of Sciences*, *119*(33), e2206500119. [{{< fa link title="link" >}}](https://doi.org/10.1073/pnas.2206500119)

**Dunnett, S.**, Holland, R. A., Taylor, G., & Eigenbrod, F. (2022c). Reply to Niebuhr et al.: Infrastructure impacts must always be assessed locally. *Proceedings of the National Academy of Sciences*, *119*(48), e2214469119. [{{< fa link title="link" >}}](https://doi.org/10.1073/pnas.2214469119)

# 2021

Delafield, G., Donnison, C., Roddis, P., Arvanitopoulos, T., Sfyridis, A., **Dunnett, S.**, Ball, T., & Logan, K. G. (2021). Conceptual framework for balancing society and nature in net-zero energy transitions. *Environmental Science & Policy*, *125*, 189–201. [{{< fa link title="link" >}}](https://doi.org/10.1016/j.envsci.2021.08.021)

# 2020

**Dunnett, S.**, Sorichetta, A., Taylor, G., & Eigenbrod, F. (2020). Harmonised global datasets of wind and solar farm locations and power. *Scientific Data*, *7*(130). [{{< fa link title="link" >}}](https://doi.org/10.1038/s41597-020-0469-8)

Eigenbrod, F., Beckmann, M., **Dunnett, S.**, Graham, L., Holland, R. A., Meyfroidt, P., Seppelt, R., Song, X.-P., Spake, R., Václavík, T., & Verburg, P. H. (2020). Identifying agricultural frontiers for modeling global cropland expansion. *One Earth*, *3*(4), 504–514. [{{< fa link title="link" >}}](https://doi.org/10.1016/j.oneear.2020.09.006)

# Theses {{< fa graduation-cap >}}

**Dunnett, S.** (2020). *Assessing potential spatial trade-offs between renewable energy expansion and biodiversity conservation* [PhD thesis, University of Southampton]. [{{< fa file-pdf title="pdf link" >}}](https://eprints.soton.ac.uk/446664/1/SebastianDunnett_PhD_Thesis_Sep20.pdf)

**Dunnett, S.** (2012). *Can biodiversity offsetting follow in carbon’s footprints?* [Master's thesis]. Imperial College London. [{{< fa file-pdf title="pdf link" >}}](resources/Dunnett12_thesis_final.pdf)




